version: '3.8'

networks:
  weathertago-network:
    driver: bridge
    name: weathertago-network

services:
  weathertago-app:
    image: ysjjw2003/weathertago:${TAG}
    container_name: weathertago-app
    ports: # 외부까지 연결 / expose : 컨테이너끼리만 연결
      - "8080:8080"
#    env_file:
#      - .env
    networks:
      - weathertago-network
    restart: always # 컨테이너가 종료되면 항상 재시작

#  redis:
#    image: redis:latest
#    container_name: redis
#    command: redis-server /usr/local/etc/redis/redis.conf
#    volumes:
#      - ./redis.conf:/usr/local/etc/redis/redis.conf # redis 데이터 저장 경로
#    ports:
#      - "6379:6379"
#    networks:
#      - weathertago-network
